export enum DoctorOnboardingStatus {
  NOT_STARTED = "NOT_STARTED",
  BASIC_INFO = "BASIC_INFO",
  DOCUMENTS_PENDING = "DOCUMENTS_PENDING",
  SUBMITTED = "SUBMITTED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}
