export enum NotificationType {
  APPOINTMENT = "APPOINTMENT",
  PAYMENT = "PAYMENT",
  CHAT = "CHAT",
  SYSTEM = "SYSTEM",
  APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED",
  APPOINTMENT_RESCHEDULED = "APPOINTMENT_RESCHEDULED"
}
