export enum NotificationType {
  APPOINTMENT = "APPOINTMENT",
  PAYMENT = "PAYMENT",
  CHAT = "CHAT",
  SYSTEM = "SYSTEM",
  APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED",
  APPOINTMENT_RESCHEDULED = "APPOINTMENT_RESCHEDULED",
  APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED",
  PRESCRIPTION = "PRESCRIPTION",
  DOCTOR_REGISTRATION = "DOCTOR_REGISTRATION",
  DOCTOR_APPROVED = "DOCTOR_APPROVED",
  DOCTOR_REJECTED = "DOCTOR_REJECTED",
  DOCTOR_PROFILE_UPDATED = "DOCTOR_PROFILE_UPDATED",
}
