import { DoctorOnboardingStatus } from "../enums/DoctorOnboardingStatus";
import { DoctorVerificationStatus } from "../enums/DoctorVerificationStatus";
import { ValidationError, InvalidStateTransitionError } from "../errors/DomainError";

export class Doctor {
  private constructor(
    private readonly id: string,
    private readonly userId: string,
    public specialty: string,
    public qualification: string,
    public experience: number,
    public consultationFee: number,
    public registrationNumber: string,
    public licenseDocument: string | null,
    public certifications: string[],
    public aboutMe: string,
    public profilePhoto: string | null,
    public onboardingStatus: DoctorOnboardingStatus,
    public verificationStatus: DoctorVerificationStatus,
    public verifiedBy: string | null = null,
    public verifiedAt: Date | null = null,
    public rejectionReason: string | null = null
  ) {}

  /**
   * ✅ DDD Factory Method for reconstruction
   * Ensures domain invariants are maintained when rehydrating from persistence.
   */
  static rehydrate(data: {
    id: string;
    userId: string;
    specialty: string | null;
    qualification: string | null;
    experience: number | null;
    consultationFee: number | null;
    registrationNumber: string | null;
    licenseDocument: string | null;
    certifications: string[] | null;
    aboutMe: string | null;
    profilePhoto: string | null;
    onboardingStatus: DoctorOnboardingStatus;
    verificationStatus: DoctorVerificationStatus;
    verifiedBy?: string | null;
    verifiedAt?: Date | null;
    rejectionReason?: string | null;
  }): Doctor {
    // Domain handles default logic for missing/null fields during reconstruction
    return new Doctor(
      data.id,
      data.userId,
      data.specialty || "",
      data.qualification || "",
      data.experience || 0,
      data.consultationFee || 0,
      data.registrationNumber || "",
      data.licenseDocument,
      data.certifications || [],
      data.aboutMe || "",
      data.profilePhoto,
      data.onboardingStatus,
      data.verificationStatus,
      data.verifiedBy || null,
      data.verifiedAt || null,
      data.rejectionReason || null
    );
  }

  /**
   * Factory method for starting new doctor onboarding
   */
  static startOnboarding(userId: string): Doctor {
    return new Doctor(
      "", // ID generated by DB
      userId,
      "",
      "",
      0,
      0,
      "",
      null,
      [],
      "",
      null,
      DoctorOnboardingStatus.BASIC_INFO,
      DoctorVerificationStatus.PENDING
    );
  }

  // -------------------------
  // GETTERS
  // -------------------------
  getId(): string {
    return this.id;
  }

  getUserId(): string {
    return this.userId;
  }

  // -------------------------
  // BUSINESS METHODS
  // -------------------------
  startBasicInfo() {
    if (this.onboardingStatus === DoctorOnboardingStatus.NOT_STARTED) {
      this.onboardingStatus = DoctorOnboardingStatus.BASIC_INFO;
    }
  }

  updateBasicInfo(data: {
    specialty: string;
    qualification: string;
    experience: number;
    consultationFee: number;
    registrationNumber: string;
    aboutMe: string;
  }) {
    this.specialty = data.specialty;
    this.qualification = data.qualification;
    this.experience = data.experience;
    this.consultationFee = data.consultationFee;
    this.registrationNumber = data.registrationNumber;
    this.aboutMe = data.aboutMe;

    this.completeBasicInfo();
  }

  updateProfile(updates: Partial<{
    specialty: string;
    qualification: string;
    experience: number;
    consultationFee: number;
    registrationNumber: string;
    aboutMe: string;
  }>) {
    if (updates.specialty !== undefined) this.specialty = updates.specialty;
    if (updates.qualification !== undefined) this.qualification = updates.qualification;
    if (updates.experience !== undefined) this.experience = updates.experience;
    if (updates.consultationFee !== undefined) this.consultationFee = updates.consultationFee;
    if (updates.registrationNumber !== undefined) this.registrationNumber = updates.registrationNumber;
    if (updates.aboutMe !== undefined) this.aboutMe = updates.aboutMe;
  }

  completeBasicInfo() {
    this.onboardingStatus = DoctorOnboardingStatus.DOCUMENTS_PENDING;
  }

  addLicenseDocument(url: string) {
    this.licenseDocument = url;
    this.completeBasicInfo();
  }

  addProfilePhoto(url: string) {
    this.profilePhoto = url;
  }

  /**
   * ✅ Explicitly update profile photo
   */
  updateProfilePhoto(url: string) {
    this.profilePhoto = url;
  }

  addCertifications(urls: string[]) {
    this.certifications = [...this.certifications, ...urls];
  }

  advanceOnboardingStep() {
    if (this.onboardingStatus === DoctorOnboardingStatus.NOT_STARTED) {
      this.onboardingStatus = DoctorOnboardingStatus.BASIC_INFO;
    } else if (this.onboardingStatus === DoctorOnboardingStatus.BASIC_INFO) {
      this.onboardingStatus = DoctorOnboardingStatus.DOCUMENTS_PENDING;
    }
  }

  updateDocuments(data: {
    licenseDocument?: string;
    profilePhoto?: string;
    certifications?: string[];
  }) {
    if (data.licenseDocument) this.addLicenseDocument(data.licenseDocument);
    if (data.profilePhoto) this.addProfilePhoto(data.profilePhoto);
    if (data.certifications) this.addCertifications(data.certifications);
    
    // Always advance to documents pending if license is present
    if (this.licenseDocument) {
      this.onboardingStatus = DoctorOnboardingStatus.DOCUMENTS_PENDING;
    }
  }

  submitForVerification() {
    if (this.onboardingStatus !== DoctorOnboardingStatus.DOCUMENTS_PENDING) {
      throw new InvalidStateTransitionError("Upload documents before submitting for verification");
    }

    if (!this.specialty || !this.registrationNumber || !this.qualification || this.experience === 0) {
      throw new ValidationError("Basic profile must be completed before verification");
    }

    if (!this.licenseDocument) {
      throw new ValidationError("License document not uploaded");
    }

    this.onboardingStatus = DoctorOnboardingStatus.SUBMITTED;
    this.verificationStatus = DoctorVerificationStatus.PENDING;
    this.rejectionReason = null;
  }

  approve(adminId: string) {
    if (this.verificationStatus !== DoctorVerificationStatus.PENDING) {
      throw new Error("Doctor not pending verification");
    }

    this.verificationStatus = DoctorVerificationStatus.APPROVED;
    this.onboardingStatus = DoctorOnboardingStatus.APPROVED;
    this.verifiedBy = adminId;
    this.verifiedAt = new Date();
    this.rejectionReason = null;
  }

  reject(adminId: string, reason: string) {
    if (!reason) {
      throw new Error("Rejection reason required");
    }

    this.verificationStatus = DoctorVerificationStatus.REJECTED;
    this.onboardingStatus = DoctorOnboardingStatus.REJECTED;
    this.verifiedBy = adminId;
    this.verifiedAt = new Date();
    this.rejectionReason = reason;
  }
}
